name: 'Issue Links'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tkt-actions/add-issue-links@v@v1.6.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          resolve: "true"
